# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/x/git/smash

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/x/git/smash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/git/smash/CMakeFiles /home/x/git/smash/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/x/git/smash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named smash

# Build rule for target.
smash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smash
.PHONY : smash

# fast build rule for target.
smash/fast:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/build
.PHONY : smash/fast

common.o: common.c.o
.PHONY : common.o

# target to build an object file
common.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/common.c.o
.PHONY : common.c.o

common.i: common.c.i
.PHONY : common.i

# target to preprocess a source file
common.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/common.c.i
.PHONY : common.c.i

common.s: common.c.s
.PHONY : common.s

# target to generate assembly for a file
common.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/common.c.s
.PHONY : common.c.s

context.o: context.c.o
.PHONY : context.o

# target to build an object file
context.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/context.c.o
.PHONY : context.c.o

context.i: context.c.i
.PHONY : context.i

# target to preprocess a source file
context.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/context.c.i
.PHONY : context.c.i

context.s: context.c.s
.PHONY : context.s

# target to generate assembly for a file
context.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/context.c.s
.PHONY : context.c.s

filters.o: filters.c.o
.PHONY : filters.o

# target to build an object file
filters.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/filters.c.o
.PHONY : filters.c.o

filters.i: filters.c.i
.PHONY : filters.i

# target to preprocess a source file
filters.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/filters.c.i
.PHONY : filters.c.i

filters.s: filters.c.s
.PHONY : filters.s

# target to generate assembly for a file
filters.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/filters.c.s
.PHONY : filters.c.s

mem.o: mem.c.o
.PHONY : mem.o

# target to build an object file
mem.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/mem.c.o
.PHONY : mem.c.o

mem.i: mem.c.i
.PHONY : mem.i

# target to preprocess a source file
mem.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/mem.c.i
.PHONY : mem.c.i

mem.s: mem.c.s
.PHONY : mem.s

# target to generate assembly for a file
mem.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/mem.c.s
.PHONY : mem.c.s

paint.o: paint.c.o
.PHONY : paint.o

# target to build an object file
paint.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/paint.c.o
.PHONY : paint.c.o

paint.i: paint.c.i
.PHONY : paint.i

# target to preprocess a source file
paint.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/paint.c.i
.PHONY : paint.c.i

paint.s: paint.c.s
.PHONY : paint.s

# target to generate assembly for a file
paint.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/paint.c.s
.PHONY : paint.c.s

reverse.o: reverse.c.o
.PHONY : reverse.o

# target to build an object file
reverse.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/reverse.c.o
.PHONY : reverse.c.o

reverse.i: reverse.c.i
.PHONY : reverse.i

# target to preprocess a source file
reverse.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/reverse.c.i
.PHONY : reverse.c.i

reverse.s: reverse.c.s
.PHONY : reverse.s

# target to generate assembly for a file
reverse.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/reverse.c.s
.PHONY : reverse.c.s

segment.o: segment.c.o
.PHONY : segment.o

# target to build an object file
segment.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/segment.c.o
.PHONY : segment.c.o

segment.i: segment.c.i
.PHONY : segment.i

# target to preprocess a source file
segment.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/segment.c.i
.PHONY : segment.c.i

segment.s: segment.c.s
.PHONY : segment.s

# target to generate assembly for a file
segment.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/segment.c.s
.PHONY : segment.c.s

smash.o: smash.c.o
.PHONY : smash.o

# target to build an object file
smash.c.o:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/smash.c.o
.PHONY : smash.c.o

smash.i: smash.c.i
.PHONY : smash.i

# target to preprocess a source file
smash.c.i:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/smash.c.i
.PHONY : smash.c.i

smash.s: smash.c.s
.PHONY : smash.s

# target to generate assembly for a file
smash.c.s:
	$(MAKE) -f CMakeFiles/smash.dir/build.make CMakeFiles/smash.dir/smash.c.s
.PHONY : smash.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... smash"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... context.o"
	@echo "... context.i"
	@echo "... context.s"
	@echo "... filters.o"
	@echo "... filters.i"
	@echo "... filters.s"
	@echo "... mem.o"
	@echo "... mem.i"
	@echo "... mem.s"
	@echo "... paint.o"
	@echo "... paint.i"
	@echo "... paint.s"
	@echo "... reverse.o"
	@echo "... reverse.i"
	@echo "... reverse.s"
	@echo "... segment.o"
	@echo "... segment.i"
	@echo "... segment.s"
	@echo "... smash.o"
	@echo "... smash.i"
	@echo "... smash.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

